export default class Estrutura {
  static filtro = ['All', 'AL.', 'Cobre', 'Aço', 'Placa', 'Motor', 'N'];

  static tabelaImport = {
    1: {
      id: 1,
      nome: 'Latinha',
      filtraPor: 'AL.',
      idRR: '24',
      precoCompra: '9.00',
      precoVenda: '10.75',
      sort: '1',
    },
    2: {
      id: 2,
      nome: 'Cobre encapado',
      filtraPor: 'Cobre',
      idRR: '1',
      precoCompra: '13.00',
      precoVenda: '18.50',
      sort: '2',
    },
    3: {
      id: 3,
      nome: 'Cobre misto',
      filtraPor: 'Cobre',
      idRR: '3',
      precoCompra: '38.00',
      precoVenda: '52.00',
      sort: '3',
    },
    4: {
      id: 4,
      nome: 'Cobre 1°',
      filtraPor: 'Cobre',
      idRR: '4',
      precoCompra: '40.00',
      precoVenda: '54.00',
      sort: '4',
    },
    5: {
      id: 5,
      nome: 'AL. Panela',
      filtraPor: 'AL.',
      idRR: '13',
      precoCompra: '8.00',
      precoVenda: '11.00',
      sort: '5',
    },
    6: {
      id: 6,
      nome: 'AL. Duro',
      filtraPor: 'AL.',
      idRR: '17',
      precoCompra: '5.00',
      precoVenda: '7.80',
      sort: '6',
    },
    7: {
      id: 7,
      nome: 'AL. Perfil 1°',
      filtraPor: 'AL.',
      idRR: '9',
      precoCompra: '10.00',
      precoVenda: '13.40',
      sort: '7',
    },
    8: {
      id: 8,
      nome: 'AL. Perfil pintado',
      filtraPor: 'AL.',
      idRR: '11',
      precoCompra: '9.00',
      precoVenda: '12.10',
      sort: '8',
    },
    9: {
      id: 9,
      nome: 'AL. Perfil misto',
      filtraPor: 'AL.',
      idRR: '0',
      precoCompra: '4.50',
      precoVenda: '4.50',
      sort: '10',
    },
    10: {
      id: 10,
      nome: 'AL. Perfil c/ parafuso',
      filtraPor: 'AL.',
      idRR: '0',
      precoCompra: '7.00',
      precoVenda: '7.00',
      sort: '99',
    },
    11: {
      id: 11,
      nome: 'AL. Chaparia',
      filtraPor: 'AL.',
      idRR: '15',
      precoCompra: '6.00',
      precoVenda: '8.00',
      sort: '9',
    },
    12: {
      id: 12,
      nome: 'AL. Roda',
      filtraPor: 'AL.',
      idRR: '19',
      precoCompra: '8.50',
      precoVenda: '13.50',
      sort: '11',
    },
    13: {
      id: 13,
      nome: 'AL. Spray',
      filtraPor: 'AL.',
      idRR: '0',
      precoCompra: '5.00',
      precoVenda: '5.00',
      sort: '12',
    },
    14: {
      id: 14,
      nome: 'AL. Spray sujo',
      filtraPor: 'AL.',
      idRR: '0',
      precoCompra: '1.50',
      precoVenda: '1.50',
      sort: '13',
    },
    15: {
      id: 15,
      nome: 'AL. Persiana',
      filtraPor: 'AL.',
      idRR: '22',
      precoCompra: '1.00',
      precoVenda: '1.50',
      sort: '14',
    },
    16: {
      id: 16,
      nome: 'AL. Cavaco',
      filtraPor: 'AL.',
      idRR: '0',
      precoCompra: '1.50',
      precoVenda: '1.50',
      sort: '15',
    },
    17: {
      id: 17,
      nome: 'Bateria',
      filtraPor: 'N',
      idRR: '28',
      precoCompra: '3.00',
      precoVenda: '3.60',
      sort: '16',
    },
    18: {
      id: 18,
      nome: 'Chumbo',
      filtraPor: 'N',
      idRR: '0',
      precoCompra: '4.50',
      precoVenda: '4.50',
      sort: '17',
    },
    19: {
      id: 19,
      nome: 'Antimónio',
      filtraPor: 'N',
      idRR: '27',
      precoCompra: '3.50',
      precoVenda: '3.50',
      sort: '18',
    },
    20: {
      id: 20,
      nome: 'Aço inox',
      filtraPor: 'Aço',
      idRR: '31',
      precoCompra: '2.00',
      precoVenda: '2.70',
      sort: '19',
    },
    21: {
      id: 21,
      nome: 'Aço inox ferroso',
      filtraPor: 'Aço',
      idRR: '32',
      precoCompra: '0.50',
      precoVenda: '0.70',
      sort: '20',
    },
    22: {
      id: 22,
      nome: 'Placa de computador',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '10.00',
      precoVenda: '10.00',
      sort: '21',
    },
    23: {
      id: 23,
      nome: 'Placa pesada',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '3.00',
      precoVenda: '3.00',
      sort: '22',
    },
    24: {
      id: 24,
      nome: 'Placa marrom',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '1.00',
      precoVenda: '1.00',
      sort: '23',
    },
    25: {
      id: 25,
      nome: 'Celular',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '1.00',
      precoVenda: '1.00',
      sort: '24',
    },
    26: {
      id: 26,
      nome: 'Tablet',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '2.00',
      precoVenda: '2.00',
      sort: '25',
    },
    27: {
      id: 27,
      nome: 'Moldem',
      filtraPor: 'Placa',
      idRR: '0',
      precoCompra: '1.00',
      precoVenda: '1.00',
      sort: '26',
    },
    28: {
      id: 28,
      nome: 'Motor geladeira',
      filtraPor: 'Motor',
      idRR: '0',
      precoCompra: '1.50',
      precoVenda: '1.50',
      sort: '27',
    },
    29: {
      id: 29,
      nome: 'Motor geladeira LP',
      filtraPor: 'Motor',
      idRR: '0',
      precoCompra: '0.75',
      precoVenda: '0.75',
      sort: '28',
    },
    30: {
      id: 30,
      nome: 'Motor ar-condicionado',
      filtraPor: 'Motor',
      idRR: '0',
      precoCompra: '2.00',
      precoVenda: '2.00',
      sort: '29',
    },
    31: {
      id: 31,
      nome: 'Motor geladeira P',
      filtraPor: 'Motor',
      idRR: '132',
      precoCompra: '0',
      precoVenda: '15.00',
      sort: '30',
    },
    32: {
      id: 32,
      nome: 'Motor geladeira M',
      filtraPor: 'Motor',
      idRR: '133',
      precoCompra: '0',
      precoVenda: '0',
      sort: '31',
    },
    33: {
      id: 33,
      nome: 'Motor geladeira P LP',
      filtraPor: 'Motor',
      idRR: '138',
      precoCompra: '0',
      precoVenda: '7.00',
      sort: '32',
    },
    34: {
      id: 34,
      nome: 'Motor elétrico',
      filtraPor: 'Motor',
      idRR: '0',
      precoCompra: '1.50',
      precoVenda: '1.50',
      sort: '33',
    },
    35: {
      id: 35,
      nome: 'Garrafa',
      filtraPor: 'N',
      idRR: '0',
      precoCompra: '0.50',
      precoVenda: '0.60',
      sort: '34',
    },
    36: {
      id: 36,
      nome: 'Garrafa mista',
      filtraPor: 'N',
      idRR: '0',
      precoCompra: '0.05',
      precoVenda: '0.10',
      sort: '35',
    },
    37: {
      id: 37,
      nome: 'Radiador al/cobre',
      filtraPor: 'Cobre',
      idRR: '0',
      precoCompra: '13.00',
      precoVenda: '0.10',
      sort: '36',
    },
  };
}
